CREATE  TABLE NOMINEES (
		number INT NOT NULL PRIMARY KEY,
		name VARCHAR(100) NOT NULL,
		Bdate  DATE NOT NULL,
		nationality VARCHAR(50) NOT NULL,
		Fscience VARCHAR(50)  NOT NULL
);

CREATE  TABLE AWARDS (
		number INT NOT NULL PRIMARY KEY,
		category VARCHAR(50) NOT NULL,
		Dname  VARCHAR(50)  NOT NULL
);

CREATE  TABLE GLOBAL_ORGANIZATIONS(
		number INT NOT NULL PRIMARY KEY,
		name VARCHAR(50) NOT NULL,
		location  VARCHAR(100) NOT NULL,
		Cinformation VARCHAR(100)  NOT NULL
);

CREATE  TABLE COMMUNITE (
		number INT NOT NULL PRIMARY KEY,
		member VARCHAR(100) NOT NULL,
		criteria  VARCHAR(50)  NOT NULL
);

CREATE  TABLE EVALUATION (
		Edate  DATE NOT NULL,
		result VARCHAR(50)  NOT NULL,
		N_number INT NOT NULL,
		C_number INT NOT NULL ,
		A_number INT NOT NULL ,
		FOREIGN KEY (N_number) REFERENCES NOMINEES(number) ON DELETE CASCADE,
		FOREIGN KEY (C_number) REFERENCES COMMUNITE(number) ON DELETE CASCADE,
		FOREIGN KEY (A_number) REFERENCES AWARDS(number) ON DELETE CASCADE );


CREATE  TABLE SUGGEST (
		number INT NOT NULL PRIMARY KEY,
		Sdate DATE NOT NULL,
		N_number INT NOT NULL,
		O_number INT NOT NULL,
		A_number INT NOT NULL ,
		FOREIGN KEY (O_number) REFERENCES  GLOBAL_ORGANIZATIONS(number) ON DELETE CASCADE,
		FOREIGN KEY (N_number) REFERENCES NOMINEES(number) ON DELETE CASCADE,
		FOREIGN KEY (A_number) REFERENCES AWARDS(number) ON DELETE CASCADE	
);

